[tools]
cookiecutter="latest"
flux2="latest"
helm="latest"
k3d="latest"
k9s="latest"
kind="latest"
krew="latest"
kubectl= "latest"
kustomize="latest"
node = "latest"
pipx="latest"
python="3.12.10"
slsa-verifier="latest"
yamllint = "latest"
yq = "latest"
jq = "latest"
uv = "latest"
cilium-cli = "latest"
fd = "latest"
eza = "latest"
bat = "latest"

[env]
_.path = "~/k8s-bash-helpers:~/git/scripts/sh"
