[env]
WINIT_X11_SCALE_FACTOR = "1"
TERM = "xterm-256color"

[window]
opacity = 1
padding.x = 0
padding.y = 0
decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
normal.family      = "FiraCode Nerd Font Mono Light"
size = 10

[general]
import = [
    "~/.config/alacritty/themes/themes/rose_pine_moon.toml"
]

[keyboard]
bindings = [
  # { key = "l", mods = "control|alt", chars = "\u001b\u000c" }
  { key = "l", mods = "control|alt", chars = "\u001b[1;5L" }
]
